[package]
name = "lightning-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
sycamore = "0.8"
#api = { git = "https://github.com/kuutamolabs/lightning-knd", package = "api" }
api = { path = "../lightning-knd/api" }
