name: Automatic merge if CI builds
on:
  push:
    branches:
      - lightning

jobs:
  wait-for-check-regexp:
    runs-on: ubuntu-latest
    if: github.actor == 'kuutamo-bot'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN_FOR_CI }}
      - name: Wait on tests
        uses: lewagon/wait-on-check-action@v1.2.0
        with:
          ref: ${{ github.sha }}
          repo-token: ${{ secrets.GH_TOKEN_FOR_CI }}
          running-workflow-name: wait-for-check-regexp
          check-regexp: (check|package).+
          verbose: true
      - name: Automerge
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout main
          git merge ${GITHUB_REF#refs/heads/}
          # attempt to reduce race condition if some other ci job already pushed in the meantime
          git pull --rebase origin main
          git push origin main
