name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          target: wasm32-unknown-unknown

      - name: Install Trunk
        uses: jetli/trunk-action@v0.2.0
        with:
          version: 'latest'

      - name: Build
        shell: sh
        run:
          trunk build --release

      - name: Archive artifact
        shell: sh
        if: runner.os == 'Linux'
        run: |
          chmod -c -R +rX "$INPUT_PATH" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
          tar \
            --dereference --hard-dereference \
            --directory "$INPUT_PATH" \
            -cvf "$RUNNER_TEMP/artifact.tar" \
            .
        env:
          INPUT_PATH: 'dist/'

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: 'github-pages'
          path: ${{ runner.temp }}/artifact.tar
          retention-days: 1000
